services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    image: redis:latest
    restart: always
    networks:
      - chat_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${CELERY_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${CELERY_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - chat_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - django
      - fastapi
    ports:
      - "80:80"
    networks:
      - chat_network
    volumes:
      - django_static:/app/static
      - django_media:/app/media

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: always
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - chat_network
    volumes:
      - .:/app
      - django_static:/app/static
      - django_media:/app/media
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    restart: always
    depends_on:
      - rabbitmq
      - redis
    networks:
      - chat_network
    volumes:
      - fastapi_logs:/app/logs
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    restart: always
    depends_on:
      - django
      - fastapi
    networks:
      - chat_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/build:/app/build
    ports:
      - "3000:3000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: celery -A aschatapp.celery worker --loglevel=info
    restart: always
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - rabbitmq
      - django
      - redis
    networks:
      - chat_network


networks:
  chat_network:

volumes:
  db_data:
  redis_data:
  rabbitmq_data:
  django_static:
  django_media:
  react_static:
  fastapi_logs:
