# Generated by Django 5.1.6 on 2025-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
